# General settings
litellm_settings:
  drop_params: true
  success_callback: []
  failure_callback: []

# Server settings
general_settings:
  master_key: sk-1234  # Change this to a secure key in production
  database_url: null

# Models
model_list:
  - model_name: phi3-mini
    litellm_params:
      model: ollama/phi3:mini
      api_key: sk-1234
  - model_name: tinyllama
    litellm_params:
      model: ollama/tinyllama
      api_key: sk-1234
  - model_name: qwen2-0.5b
    litellm_params:
      model: ollama/qwen2:0.5b
      api_key: sk-1234
  - model_name: claude-3-5-sonnet-20240620
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: llama-3-8b
    litellm_params:
      model: openrouter/meta-llama/llama-3-8b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: mistral-7b
    litellm_params:
      model: huggingface/mistralai/Mistral-7B-Instruct-v0.2
      api_key: os.environ/HUGGINGFACE_API_KEY



